[package]
name = "brunch"
version = "0.1.1"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2018"
description = "A simple micro-benchmark runner."
license = "WTFPL"
repository = "https://github.com/Blobfolio/brunch"
readme = "README.md"
exclude = [
	".gitignore",
	".righteous-sandbox.json",
	"about.toml",
	"doc",
	"justfile",
	"release",
]

[dependencies]
dactyl = "0.1.*"
num-traits = "0.2.*"
serde_json = "1.0.*"

[dependencies.serde]
version = "1.0.*"
features = [ "derive" ]
