[package]
name = "brunch"
version = "0.2.1"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2021"
rust-version = "1.56"
description = "A simple micro-benchmark runner."
license = "WTFPL"
repository = "https://github.com/Blobfolio/brunch"
readme = "README.md"
exclude = [
	".github",
	".gitignore",
	".righteous-sandbox.json",
	"about.toml",
	"doc",
	"justfile",
	"release",
]

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"

[dependencies]
dactyl = "0.2.*"
num-traits = "0.2.*"
serde_json = "1.0.*"

[dependencies.serde]
version = "1.0.*"
features = [ "derive" ]

[[bench]]
name = "fn_fib"
harness = false
