[package]
name = "brunch"
version = "0.2.6"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2021"
rust-version = "1.61"
description = "A simple micro-benchmark runner."
license = "WTFPL"
repository = "https://github.com/Blobfolio/brunch"
readme = "README.md"
exclude = [
	".github",
	".gitignore",
	".righteous-sandbox.json",
	"doc",
	"justfile",
	"release",
]

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"

[package.metadata.bashman]
name = "Brunch"
bash-dir = "./"
man-dir = "./"
credits-dir = "./"

[dependencies]
dactyl = "0.4.*"
serde_json = "1.0.*"

[dependencies.num-traits]
version = "0.2.*"
default-features = false
features = [ "std", "i128" ]

[dependencies.serde]
version = "1.0.*"
features = [ "derive" ]

[[bench]]
name = "fn_fib"
harness = false
